
os: linux
dist: bionic

language: cpp
compiler:
  - gcc

services:
  - docker

env:
  - DOCKER_IMG=osrf/ros2:nightly

before_install:
  - docker pull ${DOCKER_IMG}
  - docker images
  - docker run -it --rm --name ros2 -v ${TRAVIS_BUILD_DIR}:/home/ros2/ ${DOCKER_IMG}
  - docker ps
