
os: linux
dist: bionic

language: cpp
compiler:
  - gcc

services:
  - docker

env:
  global:
    - DOCKER_IMG=osrf/ros2:nightly
    - REPO_NAME=${PWD##*/}
    - CI_SOURCE_DIR=$(pwd)

before_install:
  - docker pull ${DOCKER_IMG}

install:
  - docker run -it --rm --name ros2 -v ${HOME}:${HOME} -e ${CI_SOURCE_DIR} -e ${REPO_NAME} ${DOCKER_IMG} bash -c 'source .github/travis.sh'
