
os: linux
dist: bionic

language: cpp
compiler:
  - gcc

services:
  - docker

env:
  - DOCKER_IMG=osrf/ros2:nightly
  - export REPO_NAME=${PWD##*/}

before_install:
  - docker pull ${DOCKER_IMG}

install:
  - docker run -it --rm --name ros2 -v ${TRAVIS_BUILD_DIR}:/home/ros2/ -e ${TRAVIS_BUILD_DIR} -e ${REPO_NAME} ${DOCKER_IMG} bash -c 'source .github/travis.sh'
