
os: linux
dist: bionic

language: cpp
compiler:
  - gcc

env:
  global:
    - REPO_NAME=${PWD##*/}

before_install:
  - export CI_SOURCE_PATH=$(pwd)

install:
  - export DOCKER_IMAGE=osrf/ros2:nightly
  - docker pull ${DOCKER_IMAGE}
  - docker run -v $HOME:$HOME -e CI_SOURCE_DIR $DOCKER_IMAGE bash -c 'cd $CI_SOURCE_DIR; source .github/travis.sh'
